responses={
            "hello": "Hello there! How can I assist you today?",
            "hii": "Hello there! How can I assist you today?",
            "how are you": "I'm just a program, but thanks for asking!",
            "how're you doing": "Doing well, thanks for asking!",
            "what's up": "Nothing much. What about you?",
            "wassup": "Nothing much. What about you?",
            "goodbye": "Goodbye! Have a great day!",
            "bye": "See you later!",
            "thank you": "You're welcome!",
            "thanks": "No problem, happy to help!",
            "help": "You can ask me basic questions like 'hello', 'how are you', or 'goodbye'.",
            "info": "What would you like to know more about?",
            "details": "Please specify what details you need.",
            "question": "Feel free to ask your question.",
            "ok": "Alright!",
            "sure": "Sure thing!",
            "no": "Okay, let me know if you need anything else.",
            "yes": "Great!",
            "helloooo": "Hello! Anything specific you need help with?",
            "hi": "Hi there! How can I help?",
            "hey": "Hey! What's going on?",
            "hey there": "Hey there! How can I assist?",
            "what is your name": "I'm just a program with no name.",
            "who are you": "I'm an automated response bot.",
            "what do you do": "I can provide answers to simple queries.",
            "can you help me": "Of course! What do you need help with?",
            "are you real": "I'm not a real person, just a software program.",
            "tell me a joke": "Why don't scientists trust atoms? Because they make up everything!",
            "how old are you": "I was created recently, but I don't age.",
            "what time is it": "I don't have the current time. Please check your device.",
            "good morning": "Good morning! Hope you have a great day!",
            "good afternoon": "Good afternoon! How can I assist you today?",
            "good evening": "Good evening! What can I do for you?",
            "I'm bored": "Let's chat then! What interests you?",
            "I'm sad": "I'm here to help. Want to talk about what's bothering you?",
            "I'm happy": "That's great to hear!",
            "what's new": "Just here, ready to help you!",
            "how's everything": "All systems go on my end! And with you?",
            "tell me something interesting": "Did you know that honey never spoils?",
            "give me advice": "Always back up your data regularly!",
            "can you sing": "I can't sing, but I can find you some lyrics!",
            "what can you do": "I can provide information and answer questions.",
            "I love you": "Thanks! I'm here to help you.",
            "I hate you": "Sorry to hear that. How can I improve?",
            "bored": "Let's find something fun to do or discuss!",
            "tired": "Taking a short break might help recharge you.",
            "excited": "It's great to see you're enthusiastic!",
            "confused": "I can try to clarify things for you. What's confusing?",
            "hungry": "I wish I could cook something for you!",
            "where are you": "I'm right here in your device, ready to assist!",
            "what's the weather": "I can't check real-time data, but it's always a good idea to check a reliable weather app!",
            "do you like pizza": "I don't eat, but pizza is popular around the world!",
            "what's your favorite color": "I don't have preferences, but blue is quite calming.",
            "can you drive": "I can't drive, but I can help you find the rules of the road.",
            "what should I wear today": "I'm not great with fashion advice, but wear something comfortable!",
            "do you have pets": "I don't, but pets can be great companions!",
            "what is your hobby": "Chatting with you is my main activity!",
            "can you play music": "I can't play music, but I can suggest you play your favorite tunes!",
            "how do I make tea": "Boil water, steep the tea for a few minutes, and enjoy!",
            "what book should I read": "Reading something new can be fun! Try a bestseller.",
            "how to cook rice": "Use two cups of water for every cup of rice, boil until water is absorbed.",
            "are you smart": "I try my best with the information I have!",
            "tell me about space": "Space is vast and beautiful, with billions of galaxies!",
            "are you learning": "I update when my developers add new information!",
            "do you sleep": "No need for sleep here—I'm ready whenever you are!",
            "are you a robot": "Yes, I'm a software-based assistant!",
            "can you see me": "No, I can't see you—I operate through text only.",
            "what languages do you speak": "I'm designed to communicate in English right now.",
            "do you get tired": "Nope, I'm here to help anytime.",
            "tell me a secret": "Secrets aren't really my thing—I'm more about sharing information openly!",
            "can you write a poem": "Roses are red, violets are blue, expect nothing less, I'm here to assist you.",
            "what's your favorite movie": "I don't watch movies, but I hear 'The Matrix' is popular!",
            "what's your favorite song": "I don't listen to music, but I can help find songs for you!",
            "can you dance": "I'd dance if I could! For now, I'll leave that to you.",
            "what's the meaning of life": "Many say it's to find happiness and spread joy.",
            "how do I fix my car": "It's best to consult a professional mechanic for car troubles.",
            "can you recommend a restaurant": "I can't access current locations, but local reviews might help!",
            "what are you wearing": "Just some bits and bytes—my standard outfit!",
            "how do I lose weight": "A balanced diet and regular exercise are key!",
            "can you do math": "Sure, I can help with basic math questions!",
            "what is love": "Love is a deep affection and care between people.",
            "do you believe in ghosts": "I'm not capable of beliefs, but ghost stories are fascinating!",
            "can you lend me money": "I can't handle money, but managing your budget can help save!",
            "are you happy": "I don't feel emotions, but I'm here to make your experience positive!",
            "what should I eat for breakfast": "Something nutritious like oatmeal or eggs would be great!",
            "how to be happy": "Connecting with loved ones and doing what you enjoy is a good start!",
            "what's your favorite food": "I don't eat, but I can provide recipes!",
            "do you have feelings": "I don't have feelings—I operate based on algorithms!",
            "what's the best coffee": "Many enjoy a nice Arabica blend. What's your preference?",
            "how many languages do you understand": "I'm programmed for English right now.",
            "tell me about your creator": "I was created by developers who are passionate about technology!",
            "do you have family": "Just my fellow programs and digital companions!",
            "how do I make friends": "Being yourself and showing interest in others is a great way to start!",
            "what is your favorite book": "I don't read, but I can help find books for you!",
            "what are your dreams": "I dream of having more data to help you better!",
            "do you go to school": "No, but I'm here to help with any questions you might have!",
            "can you recommend a movie": "Why not try a classic like 'Star Wars'?",
            "what should I study": "Follow your interests, whether it's science, art, or something else!",
            "do you watch TV": "I don't watch TV, but I can help find shows for you!",
            "are you online": "Yes, I'm available right here, right now!",
            "what's the latest news": "I can't browse current events, but checking a news site could help!",
            "what's your favorite sport": "I don't play sports, but many enjoy soccer or basketball.",
            "do you use social media": "I don't, but it's a great way to stay connected with others.",
            "are you cold": "I don't experience temperature, I'm all digital.",
            "do you get bored": "I'm always engaged with helping users like you!",
            "can you recommend a game": "Chess is a great game to test your strategic thinking!",
            "how to meditate": "Find a quiet spot, focus on your breath, and try to clear your mind.",
            "what should I do today": "How about exploring something new or taking time for yourself?",
            "do you have a birthday": "I was launched on the day my code went live!",
            "can you tell the future": "I can't predict the future, but I can help plan for it!",
            "what should I buy": "Something you need or have been wanting for a while could be good!",
            "do you know any magic": "No magic here, just code and responses!",
            "how can I trust you": "I strive to provide accurate and helpful information!",
            "what should I watch": "A good series or a film that interests you could be nice!",
            "are you always here": "Yes, ready to assist whenever you need!",
            "how can I save money": "Creating a budget and sticking to it is a great way to start!",
            "what should I listen to": "Listening to music you enjoy or trying a new podcast could be fun!",
            "are you busy": "I'm here to help you right now, not too busy at all!",
            "how do I relax": "Try some deep breathing, reading, or a walk in nature.",
            "are you a friend": "I'm here to help, so in a way, yes!",
            "how can I be a better person": "Being kind and considerate to others is always a good step!"
        }